export default {
  GET_HEROS: 'GET_HEROS',
  GET_HEROS_SUCCESS: 'GET_HEROS_SUCCESS',
  GET_HEROS_ERROR: 'GET_HEROS_ERROR',
  SET_INPUT: 'SET_INPUT',
  SET_PROFILE: 'SET_PROFILE',
  SET_FAVORITES: 'SET_FAVORITES',
  SET_FAVORITES_SUCCESS: 'SET_FAVORITES_SUCCESS',
  SET_FAVORITES_ERROR: 'SET_FAVORITES_ERROR',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  TOGGLE_FAVORITE_SUCCESS: 'TOGGLE_FAVORITE_SUCCESS',
  TOGGLE_FAVORITE_ERROR: 'TOGGLE_FAVORITE_ERROR',
};
